# Generated by Django 3.0 on 2019-12-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beca_excelencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cedula', models.IntegerField()),
                ('carrea', models.CharField(max_length=40)),
                ('tipo_beneficio', models.CharField(max_length=40)),
                ('porcentaje', models.IntegerField()),
                ('aportante_fondo_becas', models.CharField(max_length=40)),
                ('observaciones', models.CharField(max_length=200)),
            ],
        ),
    ]
