# Generated by Django 3.0 on 2019-12-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DASE', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beca_excelencia',
            old_name='carrea',
            new_name='carrera',
        ),
    ]
