# Generated by Django 3.0 on 2019-12-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASE', '0002_auto_20191215_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca_excelencia',
            name='aportante_fondo_becas',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='beca_excelencia',
            name='carrera',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='beca_excelencia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='beca_excelencia',
            name='observaciones',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='beca_excelencia',
            name='tipo_beneficio',
            field=models.CharField(max_length=100),
        ),
    ]
