# Generated by Django 3.0 on 2019-12-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASE', '0004_auto_20191215_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca_excelencia',
            name='carrera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
