# Generated by Django 3.0 on 2019-12-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DASE', '0006_auto_20191215_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='beca_excelencia',
            new_name='beca_excelencia_test',
        ),
    ]
