# Generated by Django 3.0 on 2019-12-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DASE', '0007_auto_20191221_1210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='beca_excelencia_test',
            new_name='beca_excelencia',
        ),
    ]
