# Generated by Django 3.0 on 2019-12-27 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DASE', '0011_auto_20191226_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='observaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.CharField(max_length=300)),
                ('trimestre', models.CharField(max_length=10)),
                ('cedula_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DASE.estudiantes')),
            ],
        ),
    ]
