# Generated by Django 3.0 on 2019-12-27 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DASE', '0012_observaciones'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aportantes',
            table='aportantes',
        ),
    ]
