# Generated by Django 3.0 on 2020-01-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DASE', '0014_auto_20200111_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='indices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trimestre', models.CharField(max_length=100)),
                ('iaa', models.IntegerField()),
                ('iap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='materias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('inscrita', models.BooleanField()),
                ('trimestre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='aportantes',
            name='cedula_fk',
        ),
        migrations.DeleteModel(
            name='beca_excelencia',
        ),
        migrations.RemoveField(
            model_name='observaciones',
            name='cedula_fk',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='trimestre',
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='carrera',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='tipo_beneficio',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='aportantes',
        ),
        migrations.DeleteModel(
            name='observaciones',
        ),
        migrations.AddField(
            model_name='materias',
            name='cedula_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DASE.estudiantes'),
        ),
        migrations.AddField(
            model_name='indices',
            name='cedula_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DASE.estudiantes'),
        ),
    ]
