# Generated by Django 3.0 on 2020-01-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASE', '0015_auto_20200120_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indices',
            name='iaa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='indices',
            name='iap',
            field=models.FloatField(),
        ),
    ]
